name: Run PHPUnit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: artisan_test
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_USER: artisan_test
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install

      - name: Copy environment file
        run: cp .env.example .env

      - name: Set up database
        run: |
          php artisan key:generate
          php artisan setup:test-database

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --env=testing
